using Panaderia.Models;
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddCors(options =>
    {
        options.AddDefaultPolicy( policity =>
            {
                policity
                    .AllowAnyOrigin()
                    .AllowAnyHeader()
                    .AllowAnyMethod();
            }
        );
    }
);
var app = builder.Build();
app.UseCors();

app.MapGet("/",() =>
{
    return "API Panaderia funcionando";
});

app.MapGet("/api/panaderia", () =>
{
    var productos = new List<Producto>
    {
        new Producto {
            id = 1,
            codigo = "P001",
            nombre = "Pan de chocolate",
            categoria = "Pan dulce",
            presentacion = "Unidad",
            tamano = "Mediano",
            sabor = "Chocolate",
            precio = 3.50,
            stock = 25,
            marca = "Dulce Horno",
            ingrediente = "Harina, chocolate, azúcar, leche",
            disponibilidad = "Disponible",
            descuento = 0,
            imagen = "https://images.unsplash.com/photo-1555507036-ab1f4038808a",
            descripcion = "Pan suave con sabor a chocolate."
        },
        new Producto {
            id = 2,
            codigo = "P002",
            nombre = "Pan integral",
            categoria = "Pan",
            presentacion = "Unidad",
            tamano = "Mediano",
            sabor = "Integral",
            precio = 2.00,
            stock = 40,
            marca = "Dulce Horno",
            ingrediente = "Harina integral, agua, levadura, sal",
            disponibilidad = "Disponible",
            descuento = 5,
            imagen = "https://images.unsplash.com/photo-1509440159596-0249088772ff",
            descripcion = "Pan elaborado con harina integral."
        },
        new Producto {
            id = 3,
            codigo = "P003",
            nombre = "Pan francés",
            categoria = "Pan",
            presentacion = "Unidad",
            tamano = "Pequeño",
            sabor = "Tradicional",
            precio = 0.60,
            stock = 80,
            marca = "Dulce Horno",
            ingrediente = "Harina, agua, levadura, sal",
            disponibilidad = "Disponible",
            descuento = 0,
            imagen = "https://images.unsplash.com/photo-1549931319-a545dcf3bc73",
            descripcion = "Pan tradicional de textura crujiente."
        },
        new Producto {
            id = 4,
            codigo = "P004",
            nombre = "Pan de yema",
            categoria = "Pan dulce",
            presentacion = "Unidad",
            tamano = "Mediano",
            sabor = "Dulce",
            precio = 1.50,
            stock = 35,
            marca = "Dulce Horno",
            ingrediente = "Harina, huevo, azúcar, mantequilla",
            disponibilidad = "Disponible",
            descuento = 0,
            imagen = "https://images.unsplash.com/photo-1586444248902-2f64eddc13df",
            descripcion = "Pan dulce preparado con yema de huevo."
        },
        new Producto {
            id = 5,
            codigo = "P005",
            nombre = "Croissant de chocolate",
            categoria = "Pastelería",
            presentacion = "Unidad",
            tamano = "Mediano",
            sabor = "Chocolate",
            precio = 5.50,
            stock = 18,
            marca = "Dulce Horno",
            ingrediente = "Harina, mantequilla, chocolate, azúcar",
            disponibilidad = "Disponible",
            descuento = 10,
            imagen = "https://images.unsplash.com/photo-1555507036-ab1f4038808a?ixlib=rb-4.1.0",
            descripcion = "Croissant crujiente relleno de chocolate."
        },
        new Producto {
            id = 6,
            codigo = "P006",
            nombre = "Croissant clásico",
            categoria = "Pastelería",
            presentacion = "Unidad",
            tamano = "Mediano",
            sabor = "Mantequilla",
            precio = 4.50,
            stock = 20,
            marca = "Dulce Horno",
            ingrediente = "Harina, mantequilla, leche, azúcar",
            disponibilidad = "Disponible",
            descuento = 5,
            imagen = "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=600&q=80",
            descripcion = "Croissant tradicional con textura hojaldrada."
        },
        new Producto {
            id = 7,
            codigo = "P007",
            nombre = "Donut de chocolate",
            categoria = "Donas",
            presentacion = "Unidad",
            tamano = "Mediano",
            sabor = "Chocolate",
            precio = 3.00,
            stock = 30,
            marca = "Dulce Horno",
            ingrediente = "Harina, azúcar, chocolate, huevo",
            disponibilidad = "Disponible",
            descuento = 10,
            imagen = "https://images.unsplash.com/photo-1551024506-0bccd828d307",
            descripcion = "Dona cubierta con chocolate."
        },
        new Producto {
            id = 8,
            codigo = "P008",
            nombre = "Donut de fresa",
            categoria = "Donas",
            presentacion = "Unidad",
            tamano = "Mediano",
            sabor = "Fresa",
            precio = 3.00,
            stock = 22,
            marca = "Dulce Horno",
            ingrediente = "Harina, azúcar, fresa, huevo",
            disponibilidad = "Disponible",
            descuento = 5,
            imagen = "https://images.unsplash.com/photo-1533910534207-90f31029a78e",
            descripcion = "Dona cubierta con glaseado de fresa."
        },
        new Producto {
            id = 9,
            codigo = "P009",
            nombre = "Alfajor tradicional",
            categoria = "Galletas",
            presentacion = "Unidad",
            tamano = "Mediano",
            sabor = "Manjar",
            precio = 3.50,
            stock = 28,
            marca = "Dulce Horno",
            ingrediente = "Harina, mantequilla, azúcar, manjar",
            disponibilidad = "Disponible",
            descuento = 0,
            imagen = "https://images.unsplash.com/photo-1558961363-fa8fdf82db35",
            descripcion = "Alfajor relleno de manjar blanco."
        },
        new Producto {
            id = 10,
            codigo = "P010",
            nombre = "Galleta con chispas",
            categoria = "Galletas",
            presentacion = "Unidad",
            tamano = "Grande",
            sabor = "Chocolate",
            precio = 2.50,
            stock = 45,
            marca = "Dulce Horno",
            ingrediente = "Harina, mantequilla, azúcar, chocolate",
            disponibilidad = "Disponible",
            descuento = 0,
            imagen = "https://images.unsplash.com/photo-1499636136210-6f4ee915583e",
            descripcion = "Galleta casera con chispas de chocolate."
        },
        new Producto {
            id = 11,
            codigo = "P011",
            nombre = "Muffin de vainilla",
            categoria = "Pastelería",
            presentacion = "Unidad",
            tamano = "Mediano",
            sabor = "Vainilla",
            precio = 3.50,
            stock = 20,
            marca = "Dulce Horno",
            ingrediente = "Harina, huevo, azúcar, vainilla",
            disponibilidad = "Disponible",
            descuento = 0,
            imagen = "https://images.unsplash.com/photo-1558303053-89ef17f0b225",
            descripcion = "Muffin suave con sabor a vainilla."
        },
        new Producto {
            id = 12,
            codigo = "P012",
            nombre = "Muffin de chocolate",
            categoria = "Pastelería",
            presentacion = "Unidad",
            tamano = "Mediano",
            sabor = "Chocolate",
            precio = 4.00,
            stock = 18,
            marca = "Dulce Horno",
            ingrediente = "Harina, chocolate, huevo, azúcar",
            disponibilidad = "Disponible",
            descuento = 10,
            imagen = "https://images.unsplash.com/photo-1607958996333-41aef7caefaa",
            descripcion = "Muffin de chocolate suave y esponjoso."
        },
        new Producto {
            id = 13,
            codigo = "P013",
            nombre = "Queque de vainilla",
            categoria = "Queques",
            presentacion = "Porción",
            tamano = "Mediano",
            sabor = "Vainilla",
            precio = 4.50,
            stock = 15,
            marca = "Dulce Horno",
            ingrediente = "Harina, huevo, azúcar, vainilla",
            disponibilidad = "Disponible",
            descuento = 5,
            imagen = "https://images.unsplash.com/photo-1578985545062-69928b1d9587",
            descripcion = "Porción de queque casero de vainilla."
        },
        new Producto {
            id = 14,
            codigo = "P014",
            nombre = "Torta de chocolate",
            categoria = "Tortas",
            presentacion = "Porción",
            tamano = "Grande",
            sabor = "Chocolate",
            precio = 8.00,
            stock = 10,
            marca = "Dulce Horno",
            ingrediente = "Harina, chocolate, crema, azúcar",
            disponibilidad = "Disponible",
            descuento = 15,
            imagen = "https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62",
            descripcion = "Porción de torta de chocolate con crema."
        },
        new Producto {
            id = 15,
            codigo = "P015",
            nombre = "Torta de fresa",
            categoria = "Tortas",
            presentacion = "Porción",
            tamano = "Grande",
            sabor = "Fresa",
            precio = 8.50,
            stock = 8,
            marca = "Dulce Horno",
            ingrediente = "Harina, fresa, crema, azúcar",
            disponibilidad = "Disponible",
            descuento = 10,
            imagen = "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3",
            descripcion = "Torta con crema y fresas frescas."
        },
        new Producto {
            id = 16,
            codigo = "P016",
            nombre = "Empanada de pollo",
            categoria = "Empanadas",
            presentacion = "Unidad",
            tamano = "Mediana",
            sabor = "Pollo",
            precio = 5.00,
            stock = 25,
            marca = "Dulce Horno",
            ingrediente = "Harina, pollo, cebolla, huevo",
            disponibilidad = "Disponible",
            descuento = 0,
            imagen = "https://images.unsplash.com/photo-1601050690597-df0568f70950",
            descripcion = "Empanada horneada rellena de pollo."
        },
        new Producto {
            id = 17,
            codigo = "P017",
            nombre = "Empanada de carne",
            categoria = "Empanadas",
            presentacion = "Unidad",
            tamano = "Mediana",
            sabor = "Carne",
            precio = 5.50,
            stock = 20,
            marca = "Dulce Horno",
            ingrediente = "Harina, carne, cebolla, huevo",
            disponibilidad = "Disponible",
            descuento = 5,
            imagen = "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46",
            descripcion = "Empanada horneada rellena de carne."
        },
        new Producto {
            id = 18,
            codigo = "P018",
            nombre = "Pie de manzana",
            categoria = "Postres",
            presentacion = "Porción",
            tamano = "Mediano",
            sabor = "Manzana",
            precio = 6.00,
            stock = 12,
            marca = "Dulce Horno",
            ingrediente = "Harina, manzana, canela, azúcar",
            disponibilidad = "Disponible",
            descuento = 10,
            imagen = "https://images.unsplash.com/photo-1562007908-17c67e878c88",
            descripcion = "Pie casero relleno de manzana y canela."
        },
        new Producto {
            id = 19,
            codigo = "P019",
            nombre = "Pie de limón",
            categoria = "Postres",
            presentacion = "Porción",
            tamano = "Mediano",
            sabor = "Limón",
            precio = 6.00,
            stock = 13,
            marca = "Dulce Horno",
            ingrediente = "Limón, leche condensada, galleta, huevo",
            disponibilidad = "Disponible",
            descuento = 5,
            imagen = "https://images.unsplash.com/photo-1519915028121-7d3463d20b13",
            descripcion = "Pie cremoso con sabor a limón."
        },
        new Producto {
            id = 20,
            codigo = "P020",
            nombre = "Cheesecake de fresa",
            categoria = "Postres",
            presentacion = "Porción",
            tamano = "Mediano",
            sabor = "Fresa",
            precio = 7.00,
            stock = 12,
            marca = "Dulce Horno",
            ingrediente = "Queso crema, fresa, galleta, azúcar",
            disponibilidad = "Disponible",
            descuento = 10,
            imagen = "https://images.unsplash.com/photo-1565958011703-44f9829ba187",
            descripcion = "Cheesecake cremoso con cobertura de fresa."
        },
        new Producto {
            id = 21,
            codigo = "P021",
            nombre = "Pan de ajo",
            categoria = "Pan",
            presentacion = "Unidad",
            tamano = "Mediano",
            sabor = "Ajo",
            precio = 2.50,
            stock = 30,
            marca = "Dulce Horno",
            ingrediente = "Harina, ajo, mantequilla, sal",
            disponibilidad = "Disponible",
            descuento = 0,
            imagen = "https://images.unsplash.com/photo-1573140247632-f8fd74997d5c",
            descripcion = "Pan suave con mantequilla y ajo."
        },
        new Producto {
            id = 22,
            codigo = "P022",
            nombre = "Pan de queso",
            categoria = "Pan",
            presentacion = "Unidad",
            tamano = "Pequeño",
            sabor = "Queso",
            precio = 2.00,
            stock = 35,
            marca = "Dulce Horno",
            ingrediente = "Harina, queso, leche, huevo",
            disponibilidad = "Disponible",
            descuento = 5,
            imagen = "https://images.unsplash.com/photo-1586444248902-2f64eddc13df?crop=faces",
            descripcion = "Pan pequeño relleno de queso."
        },
        new Producto {
            id = 23,
            codigo = "P023",
            nombre = "Pan de avena",
            categoria = "Pan",
            presentacion = "Unidad",
            tamano = "Mediano",
            sabor = "Avena",
            precio = 2.50,
            stock = 28,
            marca = "Dulce Horno",
            ingrediente = "Harina, avena, agua, levadura",
            disponibilidad = "Disponible",
            descuento = 5,
            imagen = "https://images.unsplash.com/photo-1509440159596-0249088772ff?crop=faces",
            descripcion = "Pan preparado con avena."
        },
        new Producto {
            id = 24,
            codigo = "P024",
            nombre = "Pan de quinua",
            categoria = "Pan",
            presentacion = "Unidad",
            tamano = "Mediano",
            sabor = "Quinua",
            precio = 3.00,
            stock = 20,
            marca = "Dulce Horno",
            ingrediente = "Harina, quinua, agua, levadura",
            disponibilidad = "Disponible",
            descuento = 10,
            imagen = "https://images.unsplash.com/photo-1549931319-a545dcf3bc73?crop=faces",
            descripcion = "Pan artesanal elaborado con quinua."
        },
        new Producto {
            id = 25,
            codigo = "P025",
            nombre = "Brioche",
            categoria = "Pan dulce",
            presentacion = "Unidad",
            tamano = "Mediano",
            sabor = "Mantequilla",
            precio = 4.00,
            stock = 18,
            marca = "Dulce Horno",
            ingrediente = "Harina, mantequilla, huevo, azúcar",
            disponibilidad = "Disponible",
            descuento = 5,
            imagen = "https://images.unsplash.com/photo-1608198093002-ad4e005484ec",
            descripcion = "Pan dulce y suave estilo brioche."
        },
        new Producto {
            id = 26,
            codigo = "P026",
            nombre = "Roll de canela",
            categoria = "Pastelería",
            presentacion = "Unidad",
            tamano = "Mediano",
            sabor = "Canela",
            precio = 4.50,
            stock = 16,
            marca = "Dulce Horno",
            ingrediente = "Harina, canela, azúcar, mantequilla",
            disponibilidad = "Disponible",
            descuento = 10,
            imagen = "https://images.unsplash.com/photo-1509365465985-25d11c17e812",
            descripcion = "Roll dulce con canela y azúcar."
        },
        new Producto {
            id = 27,
            codigo = "P027",
            nombre = "Brownie clásico",
            categoria = "Postres",
            presentacion = "Porción",
            tamano = "Mediano",
            sabor = "Chocolate",
            precio = 4.50,
            stock = 25,
            marca = "Dulce Horno",
            ingrediente = "Chocolate, harina, huevo, azúcar",
            disponibilidad = "Disponible",
            descuento = 5,
            imagen = "https://images.unsplash.com/photo-1564355808539-22fda35bed7e",
            descripcion = "Brownie de chocolate con textura suave."
        },
        new Producto {
            id = 28,
            codigo = "P028",
            nombre = "Brownie con nueces",
            categoria = "Postres",
            presentacion = "Porción",
            tamano = "Mediano",
            sabor = "Chocolate y nueces",
            precio = 5.50,
            stock = 20,
            marca = "Dulce Horno",
            ingrediente = "Chocolate, harina, nueces, huevo",
            disponibilidad = "Disponible",
            descuento = 10,
            imagen = "https://images.unsplash.com/photo-1519869325930-281384150729",
            descripcion = "Brownie de chocolate con nueces."
        },
        new Producto {
            id = 29,
            codigo = "P029",
            nombre = "Cupcake de vainilla",
            categoria = "Cupcakes",
            presentacion = "Unidad",
            tamano = "Pequeño",
            sabor = "Vainilla",
            precio = 3.00,
            stock = 30,
            marca = "Dulce Horno",
            ingrediente = "Harina, huevo, azúcar, vainilla",
            disponibilidad = "Disponible",
            descuento = 0,
            imagen = "https://images.unsplash.com/photo-1587668178277-295251f900ce",
            descripcion = "Cupcake de vainilla con crema."
        },
        new Producto {
            id = 30,
            codigo = "P030",
            nombre = "Cupcake de chocolate",
            categoria = "Cupcakes",
            presentacion = "Unidad",
            tamano = "Pequeño",
            sabor = "Chocolate",
            precio = 3.50,
            stock = 25,
            marca = "Dulce Horno",
            ingrediente = "Harina, chocolate, huevo, azúcar",
            disponibilidad = "Disponible",
            descuento = 5,
            imagen = "https://images.unsplash.com/photo-1607478900766-efe13248b125",
            descripcion = "Cupcake de chocolate con crema."
        },
        new Producto {
            id = 31,
            codigo = "P031",
            nombre = "Galleta de avena",
            categoria = "Galletas",
            presentacion = "Unidad",
            tamano = "Mediana",
            sabor = "Avena",
            precio = 2.50,
            stock = 35,
            marca = "Dulce Horno",
            ingrediente = "Avena, harina, azúcar, mantequilla",
            disponibilidad = "Disponible",
            descuento = 0,
            imagen = "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e",
            descripcion = "Galleta casera elaborada con avena."
        },
        new Producto {
            id = 32,
            codigo = "P032",
            nombre = "Galleta de coco",
            categoria = "Galletas",
            presentacion = "Unidad",
            tamano = "Mediana",
            sabor = "Coco",
            precio = 2.50,
            stock = 28,
            marca = "Dulce Horno",
            ingrediente = "Harina, coco, azúcar, mantequilla",
            disponibilidad = "Disponible",
            descuento = 5,
            imagen = "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=600&q=80",
            descripcion = "Galleta dulce con sabor a coco."
        },
        new Producto {
            id = 33,
            codigo = "P033",
            nombre = "Pan de pasas",
            categoria = "Pan dulce",
            presentacion = "Unidad",
            tamano = "Mediano",
            sabor = "Pasas",
            precio = 3.00,
            stock = 22,
            marca = "Dulce Horno",
            ingrediente = "Harina, pasas, azúcar, mantequilla",
            disponibilidad = "Disponible",
            descuento = 5,
            imagen = "https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7",
            descripcion = "Pan dulce con pasas."
        },
        new Producto {
            id = 34,
            codigo = "P034",
            nombre = "Pan de canela",
            categoria = "Pan dulce",
            presentacion = "Unidad",
            tamano = "Mediano",
            sabor = "Canela",
            precio = 3.00,
            stock = 20,
            marca = "Dulce Horno",
            ingrediente = "Harina, canela, azúcar, mantequilla",
            disponibilidad = "Disponible",
            descuento = 10,
            imagen = "https://images.unsplash.com/photo-1534432182912-63863115e106",
            descripcion = "Pan dulce con aroma y sabor a canela."
        },
        new Producto {
            id = 35,
            codigo = "P035",
            nombre = "Rosquilla azucarada",
            categoria = "Donas",
            presentacion = "Unidad",
            tamano = "Mediana",
            sabor = "Azúcar",
            precio = 2.50,
            stock = 30,
            marca = "Dulce Horno",
            ingrediente = "Harina, azúcar, huevo, leche",
            disponibilidad = "Disponible",
            descuento = 0,
            imagen = "https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=700&q=90",
            descripcion = "Rosquilla cubierta con azúcar."
        },
        new Producto {
            id = 36,
            codigo = "P036",
            nombre = "Donut rellena de manjar",
            categoria = "Donas",
            presentacion = "Unidad",
            tamano = "Mediana",
            sabor = "Manjar",
            precio = 3.50,
            stock = 24,
            marca = "Dulce Horno",
            ingrediente = "Harina, manjar, azúcar, huevo",
            disponibilidad = "Disponible",
            descuento = 10,
            imagen = "https://images.unsplash.com/photo-1527904324834-3bda86da6771",
            descripcion = "Dona rellena de manjar blanco."
        },
        new Producto {
            id = 37,
            codigo = "P037",
            nombre = "Macaron de fresa",
            categoria = "Repostería",
            presentacion = "Unidad",
            tamano = "Pequeño",
            sabor = "Fresa",
            precio = 3.00,
            stock = 30,
            marca = "Dulce Horno",
            ingrediente = "Almendra, azúcar, fresa, huevo",
            disponibilidad = "Disponible",
            descuento = 5,
            imagen = "https://images.unsplash.com/photo-1558326567-98ae2405596b",
            descripcion = "Macaron pequeño con relleno de fresa."
        },
        new Producto {
            id = 38,
            codigo = "P038",
            nombre = "Éclair de chocolate",
            categoria = "Repostería",
            presentacion = "Unidad",
            tamano = "Mediano",
            sabor = "Chocolate",
            precio = 5.00,
            stock = 15,
            marca = "Dulce Horno",
            ingrediente = "Harina, huevo, crema, chocolate",
            disponibilidad = "Disponible",
            descuento = 10,
            imagen = "https://images.unsplash.com/photo-1559622214-f8a9850965bb",
            descripcion = "Éclair relleno de crema y cubierto de chocolate."
        },
        new Producto {
            id = 39,
            codigo = "P039",
            nombre = "Tiramisú",
            categoria = "Postres",
            presentacion = "Vaso",
            tamano = "Mediano",
            sabor = "Café",
            precio = 7.50,
            stock = 12,
            marca = "Dulce Horno",
            ingrediente = "Café, mascarpone, cacao, galletas",
            disponibilidad = "Disponible",
            descuento = 10,
            imagen = "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9",
            descripcion = "Postre italiano con café y cacao."
        },
        new Producto {
            id = 40,
            codigo = "P040",
            nombre = "Flan casero",
            categoria = "Postres",
            presentacion = "Porción",
            tamano = "Mediana",
            sabor = "Vainilla",
            precio = 4.50,
            stock = 20,
            marca = "Dulce Horno",
            ingrediente = "Leche, huevo, azúcar, vainilla",
            disponibilidad = "Disponible",
            descuento = 0,
            imagen = "https://images.unsplash.com/photo-1551024506-0bccd828d307?ixid=flan",
            descripcion = "Flan casero suave con caramelo."
        },
        new Producto {
            id = 41,
            codigo = "P041",
            nombre = "Sándwich de pollo",
            categoria = "Sándwiches",
            presentacion = "Unidad",
            tamano = "Mediano",
            sabor = "Pollo",
            precio = 7.00,
            stock = 15,
            marca = "Dulce Horno",
            ingrediente = "Pan, pollo, lechuga, tomate",
            disponibilidad = "Disponible",
            descuento = 5,
            imagen = "https://images.unsplash.com/photo-1528735602780-2552fd46c7af",
            descripcion = "Sándwich de pollo con verduras frescas."
        },
        new Producto {
            id = 42,
            codigo = "P042",
            nombre = "Sándwich de jamón y queso",
            categoria = "Sándwiches",
            presentacion = "Unidad",
            tamano = "Mediano",
            sabor = "Jamón y queso",
            precio = 6.50,
            stock = 18,
            marca = "Dulce Horno",
            ingrediente = "Pan, jamón, queso, lechuga",
            disponibilidad = "Disponible",
            descuento = 0,
            imagen = "https://images.unsplash.com/photo-1481070414801-51fd732d7184",
            descripcion = "Sándwich clásico de jamón y queso."
        },
        new Producto {
            id = 43,
            codigo = "P043",
            nombre = "Pizza personal",
            categoria = "Salados",
            presentacion = "Unidad",
            tamano = "Personal",
            sabor = "Jamón y queso",
            precio = 8.00,
            stock = 12,
            marca = "Dulce Horno",
            ingrediente = "Harina, queso, jamón, tomate",
            disponibilidad = "Disponible",
            descuento = 10,
            imagen = "https://images.unsplash.com/photo-1513104890138-7c749659a591",
            descripcion = "Pizza individual con jamón y queso."
        },
        new Producto {
            id = 44,
            codigo = "P044",
            nombre = "Tequeños de queso",
            categoria = "Salados",
            presentacion = "Porción",
            tamano = "Mediano",
            sabor = "Queso",
            precio = 7.00,
            stock = 15,
            marca = "Dulce Horno",
            ingrediente = "Harina, queso, aceite",
            disponibilidad = "Disponible",
            descuento = 5,
            imagen = "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=700&q=80",
            descripcion = "Tequeños rellenos de queso."
        },
        new Producto {
            id = 45,
            codigo = "P045",
            nombre = "Torta de cumpleaños",
            categoria = "Tortas",
            presentacion = "Torta completa",
            tamano = "Grande",
            sabor = "Vainilla",
            precio = 65.00,
            stock = 5,
            marca = "Dulce Horno",
            ingrediente = "Harina, huevo, azúcar, crema",
            disponibilidad = "Disponible",
            descuento = 10,
            imagen = "https://images.unsplash.com/photo-1535141192574-5d4897c12636",
            descripcion = "Torta decorada ideal para cumpleaños."
        },
        new Producto {
            id = 46,
            codigo = "P046",
            nombre = "Torta de chocolate familiar",
            categoria = "Tortas",
            presentacion = "Torta completa",
            tamano = "Grande",
            sabor = "Chocolate",
            precio = 70.00,
            stock = 4,
            marca = "Dulce Horno",
            ingrediente = "Chocolate, harina, huevo, crema",
            disponibilidad = "Disponible",
            descuento = 15,
            imagen = "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=90",
            descripcion = "Torta familiar cubierta con chocolate."
        },
        new Producto {
            id = 47,
            codigo = "P047",
            nombre = "Caja de mini cupcakes",
            categoria = "Cupcakes",
            presentacion = "Caja x6",
            tamano = "Pequeño",
            sabor = "Vainilla",
            precio = 18.00,
            stock = 12,
            marca = "Dulce Horno",
            ingrediente = "Harina, huevo, azúcar, vainilla",
            disponibilidad = "Disponible",
            descuento = 10,
            imagen = "https://images.unsplash.com/photo-1599785209707-a456fc1337bb",
            descripcion = "Caja con seis mini cupcakes."
        },
        new Producto {
            id = 48,
            codigo = "P048",
            nombre = "Caja de alfajores",
            categoria = "Galletas",
            presentacion = "Caja x6",
            tamano = "Mediano",
            sabor = "Manjar",
            precio = 20.00,
            stock = 10,
            marca = "Dulce Horno",
            ingrediente = "Harina, mantequilla, azúcar, manjar",
            disponibilidad = "Disponible",
            descuento = 5,
            imagen = "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?auto=format&fit=crop&w=700&q=80",
            descripcion = "Caja con seis alfajores rellenos de manjar."
        },
        new Producto {
            id = 49,
            codigo = "P049",
            nombre = "Caja de donuts",
            categoria = "Donas",
            presentacion = "Caja x6",
            tamano = "Mediano",
            sabor = "Variado",
            precio = 22.00,
            stock = 10,
            marca = "Dulce Horno",
            ingrediente = "Harina, azúcar, chocolate, fresa",
            disponibilidad = "Disponible",
            descuento = 15,
            imagen = "https://images.unsplash.com/photo-1519915028121-7d3463d20b13?auto=format&fit=crop&w=800&q=90",
            descripcion = "Caja con seis donuts de diferentes sabores."
        },
        new Producto {
            id = 50,
            codigo = "P050",
            nombre = "Panetón artesanal",
            categoria = "Pan dulce",
            presentacion = "Unidad",
            tamano = "Grande",
            sabor = "Frutas confitadas",
            precio = 28.00,
            stock = 10,
            marca = "Dulce Horno",
            ingrediente = "Harina, frutas confitadas, pasas, mantequilla",
            disponibilidad = "Disponible",
            descuento = 10,
            imagen = "https://images.unsplash.com/photo-1549931319-a545dcf3bc73?auto=format&fit=crop&w=800&q=90",
            descripcion = "Panetón artesanal con frutas confitadas y pasas."
        }
    };
    return Results.Ok(productos);
});


var port = Environment.GetEnvironmentVariable("Port")??"10000";
app.Run($"http://0.0.0.0:{port}");
